# Mental Health Score Prediction

### Problem Statement 
    The objective of this project is to build a machine learning model that predicts a students mental health score(score is continuous from 3 to 10) based on defferent factor such as social media usage, study habits, sleep, physical activity, stress level, and other available features

### 1. Import Liabraries
   We are importing liabraries for data handling, visualization, preprocessing, medels, evaluation and saving.

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

## 2. Load the dataset
    Loading the dataset into a Pandas DataFrame so that we can inspect, clean, analyze, and prepare the data for machine learning.

In [10]:
df = pd.read_csv("../Data/Student Social Media And Mental Health Impact.csv")

In [19]:
# Inspect the first five rows 
df.head()

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
0,21,Male,Other,Undergraduate,Facebook,Networking,4.0,134,4.5,2.2,6.7,Medium,6.8
1,23,Female,Other,Graduate,LinkedIn,Education,1.6,73,7.0,2.4,8.6,Low,7.6
2,22,Male,Canada,Undergraduate,Instagram,Entertainment,4.6,166,4.0,1.8,6.7,Medium,7.0
3,18,Male,Other,High School,Snapchat,Entertainment,7.0,220,1.0,1.7,5.4,Very High,5.3
4,24,Female,Other,Graduate,Facebook,Networking,7.5,237,1.0,1.1,5.0,Very High,4.4

In [13]:
# Looking for number of rows and columns. 
# The dataset contain 5,000 records and 13 columns.
df.shape

(5000, 13)

In [20]:
# Column Names. 
df.columns

Index(['Age', 'Gender', 'Country', 'Academic_Level', 'Most_Used_Platform',
       'Purpose_Of_Use', 'Avg_Daily_Usage_Hours', 'Daily_Unlocks',
       'Study_Hours', 'Physical_Activity_Hours', 'Sleep_Hours_Per_Night',
       'Stress_Level', 'Mental_Health_Score'],
      dtype='object')

In [17]:
# Dataset Information 
# There are 7 numerical columns and 6 categorical columns. 
# The numerical columns contain integer and floating-point values, while the categorical columns have an object data type.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      5000 non-null   int64
 1   Gender                   5000 non-null   object
 2   Country                  5000 non-null   object
 3   Academic_Level           5000 non-null   object
 4   Most_Used_Platform       5000 non-null   object
 5   Purpose_Of_Use           5000 non-null   object
 6   Avg_Daily_Usage_Hours    5000 non-null   float64
 7   Daily_Unlocks            5000 non-null   int64
 8   Study_Hours              5000 non-null   float64
 9   Physical_Activity_Hours  5000 non-null   float64
 10  Sleep_Hours_Per_Night    5000 non-null   float64
 11  Stress_Level             5000 non-null   object
 12  Mental_Health_Score      5000 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 507.9+ KB

In [15]:
# Checking Missing values.
# The dataset contains no missing values. All 13 columns have 0 missing values.
df.isnull().sum()

Age                        0
Gender                     0
Country                    0
Academic_Level             0
Most_Used_Platform         0
Purpose_Of_Use             0
Avg_Daily_Usage_Hours      0
Daily_Unlocks              0
Study_Hours                0
Physical_Activity_Hours    0
Sleep_Hours_Per_Night      0
Stress_Level               0
Mental_Health_Score        0
dtype: int64

In [24]:
# Checking duplicates records. 
# The dataset contain 2 duplicate records. 
df.duplicated().sum()

np.int64(0)

In [25]:
# Remove duplicate records. 
df = df.drop_duplicates()

(4998, 13)

In [26]:
# Statistical summary.  
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000
mean,20.822129,5.078491,171.455582,3.008403,1.750760,6.634654,6.231152
std,1.736774,1.654097,42.859829,1.636831,0.668406,1.221561,1.278476
min,18.000000,1.000000,62.000000,0.300000,-0.400000,3.600000,3.600000
25%,19.000000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.000000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.000000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.000000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [28]:
# Target Variable Analysis.
# The target variable of this project is 'Mental_Health_Score'.
# The target has 4998 observations, with a mean of approximately 6.23 and a median of 6.10. 
# The score range from 3.6 to 9.4, showing variation in the target variable. 
df['Mental_Health_Score'].describe()

count    4998.000000
mean        6.231152
std         1.278476
min         3.600000
25%         5.100000
50%         6.100000
75%         7.100000
max         9.400000
Name: Mental_Health_Score, dtype: float64

In [29]:
# Gender Distribution 
# The dataset contain two gender categories: 
# Male: 2634 students 
# Female: 2364 students
df['Gender'].value_counts()

Gender
Male      2634
Female    2364
Name: count, dtype: int64

In [30]:
# Country Distrubution
# The country column contain students from multiple countries. 
df['Country'].value_counts()

Country
Other        1879
India         389
USA           354
Canada        230
Australia     198
             ...
Armenia         1
Kuwait          1
Colombia        1
Bosnia          1
Croatia         1
Name: count, Length: 111, dtype: int64

In [31]:
# Observation 
# The dataset contain 111 unique country categories. 
df['Country'].nunique()

111

In [32]:
# Academic Level Distribution 
# The dataset contains three academic-level categoris:
# Undergraduate: 3,630 students 
# Graduate: 918 students 
# High School: 450 students 
# Undergraduate students represent the largest group in the dataset. 
df['Academic_Level'].value_counts()

Academic_Level
Undergraduate    3630
Graduate          918
High School       450
Name: count, dtype: int64

In [33]:
# Most used platform distrubution 
# The dataset contains 12 different social media platforms. 
df['Most_Used_Platform'].value_counts()

Most_Used_Platform
Instagram    1130
TikTok        918
Facebook      719
LinkedIn      522
YouTube       491
Twitter       462
Snapchat      419
WhatsApp      175
LINE           50
VKontakte      40
KakaoTalk      36
WeChat         36
Name: count, dtype: int64

In [34]:
# Purpose of use distribution 
# The dataset contains four categories describing the primary purpose of social media use: 
# Entertainment: 2,551 students
# Education: 1,093 students
# Networking: 793 students
# News: 561 students
df['Purpose_Of_Use'].value_counts()

Purpose_Of_Use
Entertainment    2551
Education        1093
Networking        793
News              561
Name: count, dtype: int64

In [35]:
# Stress Level Distribution 
# The dataset contains four stress-level categories: 
# Very High: 1,621 students
# High: 1,439 students
# Medium: 1,295 students
# Low: 643 students
df['Stress_Level'].value_counts()

Stress_Level
Very High    1621
High         1439
Medium       1295
Low           643
Name: count, dtype: int64

In [36]:
# Number of unique values 
# The dataset countains both categorical and numerical variables. 
# The 'Country' column has 111 unique categories, making it the highest-cardinality categorical feature. 
# The categorical features such as 'Gender', 'Academic_level', 'Most_used_platform', 'purpose_of_use', and 'strss_level' have a relatively small number of categories.
df.nunique()

Age                          7
Gender                       2
Country                    111
Academic_Level               3
Most_Used_Platform          12
Purpose_Of_Use               4
Avg_Daily_Usage_Hours       79
Daily_Unlocks              200
Study_Hours                 76
Physical_Activity_Hours     44
Sleep_Hours_Per_Night       63
Stress_Level                 4
Mental_Health_Score         59
dtype: int64